In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9110, 9044, 9602, 1460],
 [9110, 9044, 9602, 9312],
 [9110, 4298, 9602, 4097],
 [4148, 3873, 1080, 4672, 2284],
 [4148, 3873, 1080, 4672, 946],
 [2843, 9110, 4028, 9602, 6857],
 [9683, 1388, 409, 4672]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9110 9044 9602 1460]
 [   0    0    0    0 9110 9044 9602 9312]
 [   0    0    0    0 9110 4298 9602 4097]
 [   0    0    0 4148 3873 1080 4672 2284]
 [   0    0    0 4148 3873 1080 4672  946]
 [   0    0    0 2843 9110 4028 9602 6857]
 [   0    0    0    0 9683 1388  409 4672]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 448ms/step


array([[[-0.0293834 ,  0.01571998,  0.0294087 ,  0.02824437,
         -0.0279542 , -0.03336115,  0.04941541,  0.01428847,
         -0.02935156,  0.01093731],
        [-0.0293834 ,  0.01571998,  0.0294087 ,  0.02824437,
         -0.0279542 , -0.03336115,  0.04941541,  0.01428847,
         -0.02935156,  0.01093731],
        [-0.0293834 ,  0.01571998,  0.0294087 ,  0.02824437,
         -0.0279542 , -0.03336115,  0.04941541,  0.01428847,
         -0.02935156,  0.01093731],
        [-0.0293834 ,  0.01571998,  0.0294087 ,  0.02824437,
         -0.0279542 , -0.03336115,  0.04941541,  0.01428847,
         -0.02935156,  0.01093731],
        [ 0.03624075, -0.00594151,  0.04282865,  0.04544917,
         -0.0379712 , -0.04727429, -0.0289759 ,  0.02241281,
         -0.0303583 ,  0.0328061 ],
        [-0.04200659,  0.03902452, -0.01295877,  0.0414452 ,
         -0.02158437, -0.01347581,  0.04896935,  0.0370968 ,
          0.00070221, -0.01532342],
        [-0.0423565 ,  0.04074034,  0.0255762 , -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9110, 9044, 9602, 1460])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 80ms/step


array([[-0.0293834 ,  0.01571998,  0.0294087 ,  0.02824437, -0.0279542 ,
        -0.03336115,  0.04941541,  0.01428847, -0.02935156,  0.01093731],
       [-0.0293834 ,  0.01571998,  0.0294087 ,  0.02824437, -0.0279542 ,
        -0.03336115,  0.04941541,  0.01428847, -0.02935156,  0.01093731],
       [-0.0293834 ,  0.01571998,  0.0294087 ,  0.02824437, -0.0279542 ,
        -0.03336115,  0.04941541,  0.01428847, -0.02935156,  0.01093731],
       [-0.0293834 ,  0.01571998,  0.0294087 ,  0.02824437, -0.0279542 ,
        -0.03336115,  0.04941541,  0.01428847, -0.02935156,  0.01093731],
       [ 0.03624075, -0.00594151,  0.04282865,  0.04544917, -0.0379712 ,
        -0.04727429, -0.0289759 ,  0.02241281, -0.0303583 ,  0.0328061 ],
       [-0.04200659,  0.03902452, -0.01295877,  0.0414452 , -0.02158437,
        -0.01347581,  0.04896935,  0.0370968 ,  0.00070221, -0.01532342],
       [-0.0423565 ,  0.04074034,  0.0255762 , -0.01055813,  0.0232758 ,
        -0.02074032,  0.0264515 , -0.03728616